### ISSUE TITLE
Add uniform initial rotation of the coin and angular momenta

### ISSUE THREAD

**Issue by iaroslav-ai** [iaroslav-ai/coin-experiment#1]
Thanks [Epä Järjestys](https://www.youtube.com/channel/UCuhQxsF97vKnNMNnA5rmYYA) for the comments on the experiment!

**Comment by Rojetto** [comment]
I was just about to write to you about this but after I finished researching I saw that there was already an issue about it :man_facepalming:

Anyway, since I already made it, here's a visualization of your current rotational distribution (axes might be flipped):
![image](https://user-images.githubusercontent.com/777285/35821625-f065e63e-0aa9-11e8-9f18-708ceec986d7.png)

**Comment by iaroslav-ai** [comment]
@Rojetto nice plot and thanks for letting me know! :+1: Seems indeed like it needs fixing :)

**Comment by iaroslav-ai** [comment]
This is now resolved in `momentum` branch of the repository. Thanks everyone for pointing this out!
In this branch, you can use `check_uniform_rotations.blend` in `misc` folder to verify that this is actually fixed. There, a bunch of spheres with coordinate (0.0, 0.0, z), z>0.0 is rotated around the origin using two different methods. 

Rotations as in original version:
![s3](https://user-images.githubusercontent.com/14038787/36061334-1e6e615c-0e59-11e8-9297-0f8d82d4dd54.png)

Now:
![n3](https://user-images.githubusercontent.com/14038787/36061340-31854f26-0e59-11e8-9693-bec2dd89f19b.png)

There is clearly something wrong with original version "around equator". 

See this for details:

[https://mathoverflow.net/questions/24688/efficiently-sampling-points-uniformly-from-the-surface-of-an-n-sphere](https://mathoverflow.net/questions/24688/efficiently-sampling-points-uniformly-from-the-surface-of-an-n-sphere)

**Comment by iaroslav-ai** [comment]
Added to acknowledgments.
